config/routes.rb
NaganoComfort::Application.routes.draw do

  namespace :client do
    resources :bedrooms, :transactions, only: [:index, :show]
    resources :reservations, only: [:index, :show, :new, :create]
    resources :bedrooms do
      member do
        get :check_availability
        post :check_availability
      end
    end
  end

  namespace :admin do
    resources :bedrooms, :customers, :price_variations, :reservations, :transactions
    resources :bedroom_statuses, :bedroom_types, :view_types, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root :to => 'pages#home'
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :customer, :customer_id, :description,
                  :in_date, :out_date, :nb_guests, :duration,
                  :bedrooms, :sub_total, :price_variations, :expected_end_date

  validates :customer_id, presence: true
  validates :in_date, presence: true
  validates :duration, numericality: { other_than: 0 }
  validates :nb_guests, numericality: { other_than: 0 }

  belongs_to :customer

  has_many :reservation_bedroom_rels
  has_many :bedrooms, through: :reservation_bedroom_rels, before_add: [:check_if_bedroom_available]
  has_many :transactions, class_name: 'Transaction'
  has_many :reservation_price_variation_rels
  has_many :price_variations, through: :reservation_price_variation_rels

  class << self
    define_method(:human_attribute_name) do |*args|
      return 'Number of guest(s)' if args[0] == :nb_guests

      super(*args)
    end
  end

  def check_if_bedroom_available(bedroom)
    r_start_date = self.in_date.to_date
    r_end_date = r_start_date + (self.duration.to_i).day
    unless bedroom.check_if_available?(r_start_date, r_end_date)
      errors.add("Bedroom #{bedroom.name}", "can't be added because he is not available during date range")
      # throw(:abort)
    end
  end

  validate :customer_already_have_transaction, on: :update
  validate :check_if_bedrooms_available
  # validate :check_price_variation_can_apply

  def customer_already_have_transaction
    if self.transactions.any? && customer_id_changed?
      errors.add(:customer, "can't be change because this customer already have active transaction(s) link to this reservation")
    end
  end

  def check_if_bedrooms_available
    self.bedrooms.each do |bedroom|
      self.check_if_bedroom_available(bedroom)
    end
  end

  # @TODO make sure we can still add the price variation dependant on the duration included instead of just the start date
  # def check_price_variation_can_apply
  #   self.price_variations.each do |price_variation|
  #     unless price_variation[:end_date].present?
  #       if self.in_date.to_date <= price_variation.start_date
  #         return errors.add("Price variation #{price_variation.name}", "can't be applied")
  #       end
  #     end
  #
  #     if price_variation[:end_date].present?
  #       unless (price_variation.start_date..price_variation.end_date).cover?(self.in_date.to_date)
  #         return errors.add("Price variation #{price_variation.name}", "can't be applied")
  #       end
  #     end
  #   end
  # end

  after_create :add_available_price_variation
  before_save :compute_sub_total, :compute_expected_end_date, on: [:create, :update]

  def get_day_of_week_result(price_variation)
    if price_variation.day_of_week > 0
      start_date = self.in_date.to_date
      end_date = start_date + (self.duration.to_i).day
      (start_date..end_date).to_a.select { |k| [price_variation.day_of_week.to_i - 1].include?(k.wday) }.length
    else
      nil
    end
  end

  def add_available_price_variation
    PriceVariation.all.each do |price_variation|
      if price_variation.day_of_week > 0
        nb_days_applied = self.get_day_of_week_result(price_variation)
        if nb_days_applied > 0
          self.price_variations << price_variation
        end
      else
        if self.in_date.to_date >= price_variation.start_date
          self.price_variations << price_variation
        end
      end
    end
  end

  def compute_expected_end_date
    start_date = self.in_date.to_date
    self.expected_end_date = start_date + (self.duration.to_i).day
  end

  def compute_sub_total
    self.sub_total = 0.0

    self.bedrooms.each do |bedroom|
      self.sub_total += self.calculate_bedroom_price(bedroom)
    end
  end

  def calculate_bedroom_price(bedroom)
    total = self.duration.to_i * bedroom.price_per_night.to_f

    self.price_variations.each do |price_variation|
      total += self.apply_price_variation(bedroom, price_variation)
    end

    total
  end

  def apply_price_variation(bedroom, price_variation)
    variation_total = 0.0
    bedroom_total = self.duration.to_i * bedroom.price_per_night.to_f
    amount = self.duration.to_i

    if price_variation.day_of_week > 0
      nb_days_applied = self.get_day_of_week_result(price_variation)
      new_bedroom_price = bedroom.price_per_night.to_f
      if price_variation.is_discount?
        new_bedroom_price -= price_variation.variation_amount.to_f * bedroom.price_per_night.to_f
      else
        new_bedroom_price += price_variation.variation_amount.to_f * bedroom.price_per_night.to_f
      end

      new_total = nb_days_applied * new_bedroom_price
      amount -= nb_days_applied
      new_total += amount * bedroom.price_per_night.to_f

      if new_total > bedroom_total
        variation_total = new_total - bedroom_total
      else
        variation_total = -(bedroom_total - new_total)
      end
    else
      if price_variation.is_discount?
        variation_total = -(price_variation.variation_amount.to_f * bedroom_total)
      else
        variation_total = price_variation.variation_amount.to_f * bedroom_total
      end
    end
    
    variation_total
  end
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < Admin::AdminController
  before_filter :ensure_bedrooms_data, only: [:create, :update]
  before_filter :ensure_price_variations_data, only: [:create, :update]

  def ensure_bedrooms_data
    if params[:reservation].present? && params[:reservation][:bedrooms].present?
      params[:reservation][:bedrooms] = Bedroom.find(params[:reservation][:bedrooms].reject(&:empty?))
    end
  end

  def ensure_price_variations_data
    if params[:reservation].present? && params[:reservation][:price_variations].present?
      params[:reservation][:price_variations] = PriceVariation.find(params[:reservation][:price_variations].reject(&:empty?))
    end
  end

  def index
    @pages = params[:pages].to_i
    @limit = params[:limit].to_i
    @reservations = Reservation.order(created_at: :desc).limit(@limit).offset(@pages * @limit)
    @record_count = Reservation.all.count

    respond_to do |format|
      if @reservations
        format.html
        format.js
        format.json { render json: @reservations }
      end
    end
  end

  def show
    @reservation = Reservation.find_by_id(params[:id])

    respond_to do |format|
      if @reservation
        format.html
        format.js
        format.json { render json: @reservation }
      else
        format.html { redirect_back fallback_location: admin_reservations_path, alert: "Cannot find reservation with id #{params[:id]}" }
        format.js { render text: 'reservation not found', status: :not_found }
        format.json { render json: '{"error": "reservation not found"}', status: :not_found }
      end
    end
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.create(params.require(:reservation))

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to admin_reservation_path(@reservation), notice: 'Reservation created successfully' }
        format.js { render js: "window.location='#{admin_reservation_path(@reservation)}'", status: :created }
        format.json { render json: @reservation, status: :created, location: [:admin, @reservation] }
      else
        format.html { render action: 'new', alert: @reservation.errors.full_messages.join('. ') }
        format.js { render text: @reservation.errors.full_messages.join('. '), status: :unprocessable_entity }
        format.json { render json: @reservation.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @reservation = Reservation.find_by_id(params[:id])
  end

  def update
    @reservation = Reservation.find_by_id(params[:id])

    respond_to do |format|
      if @reservation
        if @reservation.update_attributes(params.require(:reservation))
          format.html { redirect_to edit_admin_reservation_path(@reservation), notice: "Reservation #{@reservation.name} updated successfully" }
          format.js { render nothing: true, status: :ok }
          format.json { render json: @reservation, status: :ok, location: [:admin, @reservation] }
        else
          format.html { render :edit, alert: @reservation.errors.full_messages.join('. ') }
          format.js { render text: @reservation.errors.full_messages.join('. '), status: :unprocessable_entity }
          format.json { render json: @reservation.errors.full_messages, status: :unprocessable_entity }
        end
      else
        format.html { redirect_back fallback_location: admin_reservations_path, alert: "Cannot find reservation to update with id #{params[:id]}" }
        format.js { render text: 'reservation not found', status: :not_found }
        format.json { render json: '{"error": "reservation not found"}', status: :not_found }
      end
    end
  end

  def destroy
    @reservation = Reservation.find_by_id(params[:id])

    respond_to do |format|
      if @reservation
        if @reservation.destroy
          format.html { redirect_to admin_reservations_url, notice: 'Reservation deleted successfully' }
          format.js { render nothing: true, status: :ok }
          format.json { render json: @reservation, status: :ok }
        else
          format.html { redirect_to :back, alert: @reservation.errors.full_messages.join('. ') }
          format.js { render text: @reservation.errors.full_messages.join('. '), status: :unprocessable_entity }
          format.json { render json: @reservation.errors.full_messages, status: :unprocessable_entity }
        end
      else
        format.html { redirect_back fallback_location: admin_reservations_url, alert: "Cannot find reservation to delete with id #{params[:id]}" }
        format.js { render text: 'reservation to delete not found', status: :not_found }
        format.json { render json: '{"error": "reservation to delete not found"}', status: :not_found }
      end
    end
  end
end

app/controllers/client/reservations_controller.rb
class Client::ReservationsController < Client::ClientController
  before_filter :ensure_bedrooms_data, only: [:create, :update]

  def ensure_bedrooms_data
    if params[:reservation].present? && params[:reservation][:bedrooms].present?
      params[:reservation][:bedrooms] = Bedroom.find(params[:reservation][:bedrooms].reject(&:empty?))
    end
  end

  def index
    @pages = params[:pages].to_i
    @limit = params[:limit].to_i
    @reservations = Reservation.where(customer_id: @current_user_id)
    @reservations = @reservations.order(created_at: :desc).limit(@limit).offset(@pages * @limit)
    @record_count = @reservations.count

    respond_to do |format|
      if @reservations
        format.html
        format.js
        format.json { render json: @reservations }
      end
    end
  end

  def show
    @reservation = Reservation.find_by_id(params[:id])

    respond_to do |format|
      if @reservation
        format.html
        format.js
        format.json { render json: @reservation }
      else
        format.html { redirect_back fallback_location: client_reservations_path, alert: "Cannot find reservation with id #{params[:id]}" }
        format.js { render text: 'reservation not found', status: :not_found }
        format.json { render json: '{"error": "reservation not found"}', status: :not_found }
      end
    end
  end

  def new
    params.require(:bedroom_id)
    params.require(:customer_id)
    params.require(:in_date)
    params.require(:duration)

    @reservation = Reservation.new
    @reservation.customer_id = params[:customer_id]
    @reservation.in_date = params[:in_date]
    @reservation.duration = params[:duration]
    @reservation.bedrooms << Bedroom.find_by_id(params[:bedroom_id])
  end

  def create
    @reservation = Reservation.create(params.require(:reservation).except(:bedrooms))
    beds_to_add = Bedroom.find_all_by_id(params[:reservation][:bedrooms])
    @reservation.bedrooms << beds_to_add

    respond_to do |format|
      if @reservation.save
        ReservationConfirmation.reservation_confirmation_email(@current_user, @reservation).deliver
        format.html { redirect_to client_reservation_path(@reservation), notice: 'Reservation created successfully' }
        format.js { render js: "window.location='#{client_reservation_path(@reservation)}'", status: :created }
        format.json { render json: @reservation, status: :created, location: [:admin, @reservation] }
      else
        format.html { render action: 'new', alert: @reservation.errors.full_messages.join('. ') }
        format.js { render text: @reservation.errors.full_messages.join('. '), status: :unprocessable_entity }
        format.json { render json: @reservation.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def card_reservation(reservation)
    @reservation = reservation
    render partial: 'shared/reservations/card'
  end

  def get_duration(start_date, end_date)
    (end_date - start_date).to_i
  end
end

app/views/admin/reservations/_form.html.haml
.container-fluid.h-100.bg-light.text-dark
  .row.justify-content-center.align-items-center
    %h1
      = @action.capitalize
      reservation
  %hr/
  .row.justify-content-center.align-items-center.h-100
    .col.col-sm-6.col-md-6.col-lg-4.col-xl-3
      = form_for [:admin, @reservation], html: {id: "reservation-form"}, remote: true do |f|
        .input-group.mb-3
          %span.input-group-text= Reservation.human_attribute_name(:customer)
          = f.collection_select :customer_id, Customer.all, :id, :name, {}, { class: "form-select" }
        .input-group.mb-3
          %span.input-group-text= Reservation.human_attribute_name(:bedrooms)
          = f.select :bedrooms, options_from_collection_for_select(Bedroom.all, :id, :name, {selected: @reservation.bedrooms.map(&:id)}), {}, { class: 'form-select', multiple: true }
        .input-group.mb-3
          %span.input-group-text= Reservation.human_attribute_name(:price_variations)
          = f.select :price_variations, options_from_collection_for_select(PriceVariation.all, :id, :name, {selected: @reservation.price_variations.map(&:id)}), {}, { class: 'form-select', include_blank: true, multiple: true }
        .input-group.mb-3
          %span.input-group-text= Reservation.human_attribute_name(:description)
          = f.text_area :description, rows: 10, style: 'widt h:100%;', class: "form-control"
        .input-group.mb-3
          %span.input-group-text= Reservation.human_attribute_name(:in_date)
          = f.datetime_select :in_date, start_year: Time.now.year
        .input-group.mb-3
          %span.input-group-text= Reservation.human_attribute_name(:out_date)
          = f.datetime_select :out_date, start_year: Time.now.year, include_blank: true
        .input-group.mb-3
          %span.input-group-text= Reservation.human_attribute_name(:nb_guests)
          = f.number_field :nb_guests, step: 1, class: "form-control"
        .input-group.mb-3
          %span.input-group-text= Reservation.human_attribute_name(:duration)
          = f.number_field :duration, step: 1, class: "form-control"
        = f.submit submit_text(@action), class: "btn btn-primary"
        = link_to "Back", :back, class: "btn btn-danger"

app/views/admin/reservations/_table.html.haml
.table-responsive
  %table.table.caption-top
    %caption
      Reservations
      .float-end
        = render "layouts/pagination_limit"
    %thead.table-dark
      %tr
        %th{scope: "col"} #
        %th{scope: "col"}= Reservation.human_attribute_name(:customer)
        %th{scope: "col"}= Reservation.human_attribute_name(:in_date)
        %th{scope: "col"}= Reservation.human_attribute_name(:out_date)
        %th{scope: "col"}= Reservation.human_attribute_name(:nb_guests)
        %th{scope: "col"}= Reservation.human_attribute_name(:duration)
        %th{scope: "col"}= Reservation.human_attribute_name(:sub_total)
        %th{colspan: "3"}
    %tbody
      - @reservations.each do |reservation|
        %tr
          %th{scope: "row"}= reservation.id
          %td= reservation.customer.try(:name)
          %td= reservation.in_date
          %td= reservation.out_date
          %td= reservation.nb_guests
          %td= reservation.duration
          %td= number_to_currency(reservation.sub_total, unit: '$')
          %td
            .btn-group.btn-group-sm{"aria-label" => "Action buttons", role: "group"}
              = link_to 'Show', admin_reservation_path(reservation), remote: true, class: 'btn btn-success'
              = link_to 'Edit', edit_admin_reservation_path(reservation), remote: true, class: 'btn btn-warning'
              = link_to 'Delete', admin_reservation_path(reservation), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this reservation ?' }
  .d-flex.justify-content-between
    %div
      = link_to "Create new reservation", new_admin_reservation_path, remote: true, class: "btn btn-primary"
    = render "layouts/pagination_navigation"

app/views/admin/reservations/edit.html.haml
= render 'form'

app/views/admin/reservations/edit.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'form') %>');
$('form#reservation-form[data-remote="true"]').on('ajax:success', function(e, data, status, xhr) {
    // if ajax is success set the default value to the current value so it doesnt reset on the old value when an error occured.
    Array.from(e.currentTarget.elements).map((el) => el.defaultValue = el.value);
    alert('Reservation updated successfully', 'success');
}).on('ajax:error', function(e, xhr, status, error) {
    e.target.reset();
    alert(xhr.responseText, 'danger', 0);
});

app/views/admin/reservations/index.html.haml
= render "table"

app/views/admin/reservations/index.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'table') %>');

app/views/admin/reservations/new.html.haml
= render 'form'

app/views/admin/reservations/new.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'form') %>');
$('form#reservation-form[data-remote="true"]').on('ajax:error', function(e, xhr, status, error) {
    alert(xhr.responseText, 'danger', 0);
});

app/views/admin/reservations/show.html.haml
%div
  = link_to "Create new transaction", new_admin_transaction_path(reservation_id: @reservation.id, customer_id: @reservation.customer.id, total_due: @reservation.sub_total), remote: true, class: "btn btn-primary"
= card_reservation(@reservation)
= link_to 'Back', :back, class: 'btn btn-primary'

app/views/admin/reservations/show.js.erb
$('#page-content').empty();
$('#page-content').append('<div><%= link_to "Create new transaction", new_admin_transaction_path(reservation_id: @reservation.id, customer_id: @reservation.customer.id, total_due: @reservation.sub_total), remote: true, class: "btn btn-primary" %></div>');
$('#page-content').append('<%= escape_javascript(card_reservation(@reservation)) %>');
$('#page-content').append('<%= link_to 'Back', :back, remote: true, class: 'btn btn-primary' %>');