config/routes.rb
NaganoComfort::Application.routes.draw do

  namespace :client do
    resources :bedrooms, :transactions, only: [:index, :show]
    resources :reservations, only: [:index, :show, :new, :create]
    resources :bedrooms do
      member do
        get :check_availability
        post :check_availability
      end
    end
  end

  namespace :admin do
    resources :bedrooms, :customers, :price_variations, :reservations, :transactions
    resources :bedroom_statuses, :bedroom_types, :view_types, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root :to => 'pages#home'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :name, :email, :phone

  validates :name, presence: true

  has_many :reservations, dependent: :destroy
  has_many :transactions, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::AdminController
  def index
    @pages = params[:pages].to_i
    @limit = params[:limit].to_i
    @customers = Customer.order(created_at: :desc).limit(@limit).offset(@pages * @limit)
    @record_count = Customer.all.count

    respond_to do |format|
      if @customers
        format.html
        format.js
        format.json { render json: @customers }
      end
    end
  end

  def show
    @customer = Customer.find_by_id(params[:id])

    respond_to do |format|
      if @customer
        format.html
        format.js
        format.json { render json: @customer }
      else
        format.html { redirect_back fallback_location: admin_customers_path, alert: "Cannot find customer with id #{params[:id]}" }
        format.js { render text: 'customer not found', status: :not_found }
        format.json { render json: '{"error": "customer not found"}', status: :not_found }
      end
    end
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(params.require(:customer))

    respond_to do |format|
      if @customer.save
        format.html { redirect_to admin_customers_path, notice: 'customer created successfully' }
        format.js { render js: "window.location='#{admin_customers_path}'", status: :created }
        format.json { render json: @customer, status: :created, location: [:admin, @customer] }
      else
        format.html { render action: 'new', alert: @customer.errors.full_messages.join('. ') }
        format.js { render text: @customer.errors.full_messages.join('. '), status: :unprocessable_entity }
        format.json { render json: @customer.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @customer = Customer.find_by_id(params[:id])
  end

  def update
    @customer = Customer.find_by_id(params[:id])

    respond_to do |format|
      if @customer
        if @customer.update_attributes(params.require(:customer))
          format.html { redirect_to edit_admin_customer_path(@customer), notice: "customer #{@customer.name} updated successfully" }
          format.js { render nothing: true, status: :ok }
          format.json { render json: @customer, status: :ok, location: [:admin, @customer] }
        else
          format.html { render :edit, alert: @customer.errors.full_messages.join('. ') }
          format.js { render text: @customer.errors.full_messages.join('. '), status: :unprocessable_entity }
          format.json { render json: @customer.errors.full_messages, status: :unprocessable_entity }
        end
      else
        format.html { redirect_back fallback_location: admin_customers_path, alert: "Cannot find customer to update with id #{params[:id]}" }
        format.js { render text: 'customer not found', status: :not_found }
        format.json { render json: '{"error": "customer not found"}', status: :not_found }
      end
    end
  end

  def destroy
    @customer = Customer.find_by_id(params[:id])

    respond_to do |format|
      if @customer
        if @customer.destroy
          format.html { redirect_to admin_customers_url, notice: 'customer deleted successfully' }
          format.js { render nothing: true, status: :ok }
          format.json { render json: @customer, status: :ok }
        else
          format.html { redirect_to :back, alert: @customer.errors.full_messages.join('. ') }
          format.js { render text: @customer.errors.full_messages.join('. '), status: :unprocessable_entity }
          format.json { render json: @customer.errors.full_messages, status: :unprocessable_entity }
        end
      else
        format.html { redirect_back fallback_location: admin_customers_url, alert: "Cannot find customer to delete with id #{params[:id]}" }
        format.js { render text: 'customer to delete not found', status: :not_found }
        format.json { render json: '{"error": "customer to delete not found"}', status: :not_found }
      end
    end
  end
end

app/views/admin/customers/_card.html.haml
.card{style: "max-width: 18rem;"}
  .card-body
    %h5.card-title
      #{@customer.name}
  %ul.list-group.list-group-flush
    %li.list-group-item
      = "#{Customer.human_attribute_name(:email)}: #{@customer.email}"
    %li.list-group-item
      = "#{Customer.human_attribute_name(:phone)}: #{@customer.phone}"
    %li.list-group-item
      = "#{Customer.human_attribute_name(:reservations)}: "
      - if @customer.reservations.length() > 0
        %ul
          - @customer.reservations.each do |reservation|
            %li
              = link_to "Reservation for #{reservation.in_date}", admin_reservation_path(reservation), remote: true
      - else
        %span None
  .card-body
    .btn-group.btn-group-sm{"aria-label" => "Action buttons", role: "group"}
      = link_to 'Edit', edit_admin_customer_path(@customer), remote: true, class: 'btn btn-warning'
      = link_to 'Delete', admin_customer_path(@customer), class: 'btn btn-danger', method: 'delete', data: { confirm: 'Are you sure you want to delete this customer ?' }

app/views/admin/customers/_form.html.haml
.container-fluid.h-100.bg-light.text-dark
  .row.justify-content-center.align-items-center
    %h1
      = @action.capitalize
      customer
  %hr/
  .row.justify-content-center.align-items-center.h-100
    .col.col-sm-6.col-md-6.col-lg-4.col-xl-3
      = form_for [:admin, @customer], html: {id: "customer-form"}, remote: true do |f|
        .input-group.mb-3
          %span.input-group-text= Customer.human_attribute_name(:name)
          = f.text_field :name, class: "form-control"
        .input-group.mb-3
          %span.input-group-text= Customer.human_attribute_name(:email)
          = f.text_field :email, class: "form-control"
        .input-group.mb-3
          %span.input-group-text= Customer.human_attribute_name(:phone)
          = f.text_field :phone, class: "form-control"
        = f.submit submit_text(@action), class: "btn btn-primary"
        = link_to "Back", :back, class: "btn btn-danger"

app/views/admin/customers/_table.html.haml
.table-responsive
  %table.table.caption-top
    %caption
      Customers
      .float-end
        = render "layouts/pagination_limit"
    %thead.table-dark
      %tr
        %th{scope: "col"} #
        %th{scope: "col"}= Customer.human_attribute_name(:name)
        %th{scope: "col"}= Customer.human_attribute_name(:email)
        %th{scope: "col"}= Customer.human_attribute_name(:phone)
        %th{colspan: "3"}
    %tbody
      - @customers.each do |customer|
        %tr
          %th{scope: "row"}= customer.id
          %td= customer.name
          %td= customer.email
          %td= customer.phone
          %td
            .btn-group.btn-group-sm{"aria-label" => "Action buttons", role: "group"}
              = link_to 'Show', admin_customer_path(customer), remote: true, class: 'btn btn-success'
              = link_to 'Edit', edit_admin_customer_path(customer), remote: true, class: 'btn btn-warning'
              = link_to 'Delete', admin_customer_path(customer), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this customer ?' }
  .d-flex.justify-content-between
    %div
      = link_to "Create new customer", new_admin_customer_path, remote: true, class: "btn btn-primary"
    = render "layouts/pagination_navigation"

app/views/admin/customers/edit.html.haml
= render 'form'

app/views/admin/customers/edit.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'form') %>');
$('form#customer-form[data-remote="true"]').on('ajax:success', function(e, data, status, xhr) {
    // if ajax is success set the default value to the current value so it doesnt reset on the old value when an error occured.
    Array.from(e.currentTarget.elements).map((el) => el.defaultValue = el.value);
    alert('Customer <%= @customer.name %> updated successfully', 'success');
}).on('ajax:error', function(e, xhr, status, error) {
    e.target.reset();
    alert(xhr.responseText, 'danger', 0);
});

app/views/admin/customers/index.html.haml
= render "table"

app/views/admin/customers/index.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'table') %>');

app/views/admin/customers/new.html.haml
= render 'form'

app/views/admin/customers/new.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'form') %>');
$('form#customer-form[data-remote="true"]').on('ajax:error', function(e, xhr, status, error) {
    alert(xhr.responseText, 'danger', 0);
});

app/views/admin/customers/show.html.haml
= render 'card'
= link_to 'Back', :back, class: 'btn btn-primary'

app/views/admin/customers/show.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'card') %>');
$('#page-content').append('<%= link_to 'Back', :back, remote: true, class: 'btn btn-primary' %>');