config/routes.rb
NaganoComfort::Application.routes.draw do

  namespace :client do
    resources :bedrooms, :transactions, only: [:index, :show]
    resources :reservations, only: [:index, :show, :new, :create]
    resources :bedrooms do
      member do
        get :check_availability
        post :check_availability
      end
    end
  end

  namespace :admin do
    resources :bedrooms, :customers, :price_variations, :reservations, :transactions
    resources :bedroom_statuses, :bedroom_types, :view_types, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root :to => 'pages#home'
end

app/models/price_variation.rb
class PriceVariation < ActiveRecord::Base
  attr_accessible :name, :variation_amount, :start_date, :end_date, :day_of_week, :is_discount

  validates :name, presence: true
  validates :variation_amount, presence: true
  validates :start_date, presence: true

  has_many :reservation_price_variation_rels
  has_many :reservations, through: :reservation_price_variation_rels
end

app/controllers/admin/price_variations_controller.rb
class Admin::PriceVariationsController < Admin::AdminController
  def index
    @pages = params[:pages].to_i
    @limit = params[:limit].to_i
    @price_variations = PriceVariation.order(created_at: :desc).limit(@limit).offset(@pages * @limit)
    @record_count = PriceVariation.all.count

    respond_to do |format|
      if @price_variations
        format.html
        format.js
        format.json { render json: @price_variations }
      end
    end
  end

  def show
    @price_variation = PriceVariation.find_by_id(params[:id])

    respond_to do |format|
      if @price_variation
        format.html
        format.js
        format.json { render json: @price_variation }
      else
        format.html { redirect_back fallback_location: admin_price_variations_path, alert: "Cannot find price variation with id #{params[:id]}" }
        format.js { render text: 'price variation not found', status: :not_found }
        format.json { render json: '{"error": "price variation not found"}', status: :not_found }
      end
    end
  end

  def new
    @price_variation = PriceVariation.new
  end

  def create
    @price_variation = PriceVariation.create(params.require(:price_variation))

    respond_to do |format|
      if @price_variation.save
        format.html { redirect_to admin_price_variations_path, notice: 'price variation created successfully' }
        format.js { render js: "window.location='#{admin_price_variations_path}'", status: :created }
        format.json { render json: @price_variation, status: :created, location: [:admin, @price_variation] }
      else
        format.html { render action: 'new', alert: @price_variation.errors.full_messages.join('. ') }
        format.js { render text: @price_variation.errors.full_messages.join('. '), status: :unprocessable_entity }
        format.json { render json: @price_variation.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @price_variation = PriceVariation.find_by_id(params[:id])
  end

  def update
    @price_variation = PriceVariation.find_by_id(params[:id])

    respond_to do |format|
      if @price_variation
        if @price_variation.update_attributes(params.require(:price_variation))
          format.html { redirect_to edit_admin_price_variation_path(@price_variation), notice: "price variation #{@price_variation.name} updated successfully" }
          format.js { render nothing: true, status: :ok }
          format.json { render json: @price_variation, status: :ok, location: [:admin, @price_variation] }
        else
          format.html { render :edit, alert: @price_variation.errors.full_messages.join('. ') }
          format.js { render text: @price_variation.errors.full_messages.join('. '), status: :unprocessable_entity }
          format.json { render json: @price_variation.errors.full_messages, status: :unprocessable_entity }
        end
      else
        format.html { redirect_back fallback_location: admin_price_variations_path, alert: "Cannot find price variation to update with id #{params[:id]}" }
        format.js { render text: 'price variation not found', status: :not_found }
        format.json { render json: '{"error": "price variation not found"}', status: :not_found }
      end
    end
  end

  def destroy
    @price_variation = PriceVariation.find_by_id(params[:id])

    respond_to do |format|
      if @price_variation
        if @price_variation.destroy
          format.html { redirect_to admin_price_variations_url, notice: 'price variation deleted successfully' }
          format.js { render nothing: true, status: :ok }
          format.json { render json: @price_variation, status: :ok }
        else
          format.html { redirect_to :back, alert: @price_variation.errors.full_messages.join('. ') }
          format.js { render text: @price_variation.errors.full_messages.join('. '), status: :unprocessable_entity }
          format.json { render json: @price_variation.errors.full_messages, status: :unprocessable_entity }
        end
      else
        format.html { redirect_back fallback_location: admin_price_variations_url, alert: "Cannot find price variation to delete with id #{params[:id]}" }
        format.js { render text: 'price variation to delete not found', status: :not_found }
        format.json { render json: '{"error": "price variation to delete not found"}', status: :not_found }
      end
    end
  end
end

app/helpers/price_variations_helper.rb
module PriceVariationsHelper
  def day_of_the_week_mapping(nb_day)
    case nb_day
    when 1
      'Monday'
    when 2
      'Tuesday'
    when 3
      'Wednesday'
    when 4
      'Thursday'
    when 5
      'Friday'
    when 6
      'Saturday'
    when 7
      'Sunday'
    else
      nil
    end
  end

  def day_of_the_week_options
    [{ id: 0, name: "" }, { id: 1, name: "Monday" },
     { id: 2, name: "Tuesday" }, { id: 3, name: "Wednesday" },
     { id: 4, name: "Thursday" }, { id: 5, name: "Friday" },
     { id: 6, name: "Saturday" }, { id: 7, name: "Sunday" }]
  end
end

app/views/admin/price_variations/_card.html.haml
.card{style: "max-width: 18rem;"}
  .card-body
    %h5.card-title
      #{@price_variation.name}
  %ul.list-group.list-group-flush
    %li.list-group-item
      = "#{PriceVariation.human_attribute_name(:variation_amount)}: #{@price_variation.variation_amount}"
    %li.list-group-item
      = "#{PriceVariation.human_attribute_name(:start_date)}: #{@price_variation.start_date}"
    %li.list-group-item
      = "#{PriceVariation.human_attribute_name(:out_date)}: #{@price_variation.end_date}"
    %li.list-group-item
      = "#{PriceVariation.human_attribute_name(:day_of_week)}: #{day_of_the_week_mapping(@price_variation.day_of_week)}"
    %li.list-group-item
      = "#{PriceVariation.human_attribute_name(:is_discount)}: #{@price_variation.is_discount}"
  .card-body
    .btn-group.btn-group-sm{"aria-label" => "Action buttons", role: "group"}
      = link_to 'Edit', edit_admin_price_variation_path(@price_variation), remote: true, class: 'btn btn-warning'
      = link_to 'Delete', admin_price_variation_path(@price_variation), class: 'btn btn-danger', method: 'delete', data: { confirm: 'Are you sure you want to delete this price variation ?' }

app/views/admin/price_variations/_form.html.haml
.container-fluid.h-100.bg-light.text-dark
  .row.justify-content-center.align-items-center
    %h1
      = @action.capitalize
      price variation
  %hr/
  .row.justify-content-center.align-items-center.h-100
    .col.col-sm-6.col-md-6.col-lg-4.col-xl-3
      = form_for [:admin, @price_variation], html: {id: "price-variation-form"}, remote: true do |f|
        .input-group.mb-3
          %span.input-group-text= PriceVariation.human_attribute_name(:name)
          = f.text_field :name, class: "form-control"
        .input-group.mb-3
          %span.input-group-text= PriceVariation.human_attribute_name(:variation_amount)
          = f.number_field :variation_amount, step: 0.01, class: "form-control"
        .input-group.mb-3
          %span.input-group-text= PriceVariation.human_attribute_name(:start_date)
          = f.date_select :start_date
        .input-group.mb-3
          %span.input-group-text= PriceVariation.human_attribute_name(:end_date)
          = f.date_select :end_date, include_blank: true
        .input-group.mb-3
          %span.input-group-text= PriceVariation.human_attribute_name(:day_of_week)
          = f.select :day_of_week, day_of_the_week_options.collect {|d| [ d[:name], d[:id] ]}, { class: "form-control" }
        .form-check.mb-3
          = f.check_box :is_discount, class: "form-check-input"
          %label.form-check-label
            = PriceVariation.human_attribute_name(:is_discount)
        = f.submit submit_text(@action), class: "btn btn-primary"
        = link_to "Back", :back, class: "btn btn-danger"

app/views/admin/price_variations/_table.html.haml
.table-responsive
  %table.table.caption-top
    %caption
      Price Variations
      .float-end
        = render "layouts/pagination_limit"
    %thead.table-dark
      %tr
        %th{scope: "col"} #
        %th{scope: "col"}= PriceVariation.human_attribute_name(:name)
        %th{scope: "col"}= PriceVariation.human_attribute_name(:variation_amount)
        %th{scope: "col"}= PriceVariation.human_attribute_name(:start_date)
        %th{scope: "col"}= PriceVariation.human_attribute_name(:end_date)
        %th{scope: "col"}= PriceVariation.human_attribute_name(:day_of_week)
        %th{scope: "col"}= PriceVariation.human_attribute_name(:is_discount)
        %th{colspan: "3"}
    %tbody
      - @price_variations.each do |price_variation|
        %tr
          %th{scope: "row"}= price_variation.id
          %td= price_variation.name
          %td= price_variation.variation_amount
          %td= price_variation.start_date
          %td= price_variation.end_date
          %td= day_of_the_week_mapping(price_variation.day_of_week)
          %td= price_variation.is_discount
          %td
            .btn-group.btn-group-sm{"aria-label" => "Action buttons", role: "group"}
              = link_to 'Show', admin_price_variation_path(price_variation), remote: true, class: 'btn btn-success'
              = link_to 'Edit', edit_admin_price_variation_path(price_variation), remote: true, class: 'btn btn-warning'
              = link_to 'Delete', admin_price_variation_path(price_variation), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this price variation ?' }
  .d-flex.justify-content-between
    %div
      = link_to "Create new price variation", new_admin_price_variation_path, remote: true, class: "btn btn-primary"
    = render "layouts/pagination_navigation"

app/views/admin/price_variations/edit.html.haml
= render 'form'

app/views/admin/price_variations/edit.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'form') %>');
$('form#price-variation-form[data-remote="true"]').on('ajax:success', function(e, data, status, xhr) {
    // if ajax is success set the default value to the current value so it doesnt reset on the old value when an error occured.
    Array.from(e.currentTarget.elements).map((el) => el.defaultValue = el.value);
    alert('Price variation <%= @price_variation.name %> updated successfully', 'success');
}).on('ajax:error', function(e, xhr, status, error) {
    e.target.reset();
    alert(xhr.responseText, 'danger', 0);
});

app/views/admin/price_variations/index.html.haml
= render "table"

app/views/admin/price_variations/index.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'table') %>');

app/views/admin/price_variations/new.html.haml
= render 'form'

app/views/admin/price_variations/new.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'form') %>');
$('form#price-variation-form[data-remote="true"]').on('ajax:error', function(e, xhr, status, error) {
    alert(xhr.responseText, 'danger', 0);
});

app/views/admin/price_variations/show.html.haml
= render 'card'
= link_to 'Back', :back, class: 'btn btn-primary'

app/views/admin/price_variations/show.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'card') %>');
$('#page-content').append('<%= link_to 'Back', :back, remote: true, class: 'btn btn-primary' %>');