config/routes.rb
NaganoComfort::Application.routes.draw do

  namespace :client do
    resources :bedrooms, :transactions, only: [:index, :show]
    resources :reservations, only: [:index, :show, :new, :create]
    resources :bedrooms do
      member do
        get :check_availability
        post :check_availability
      end
    end
  end

  namespace :admin do
    resources :bedrooms, :customers, :price_variations, :reservations, :transactions
    resources :bedroom_statuses, :bedroom_types, :view_types, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  root :to => 'pages#home'
end

app/controllers/admin/bedroom_types_controller.rb
class Admin::BedroomTypesController < Admin::AdminController
  def index
    @pages = params[:pages].to_i
    @limit = params[:limit].to_i
    @bedroom_types = BedroomType.order(created_at: :desc).limit(@limit).offset(@pages * @limit)
    @record_count = BedroomType.all.count

    respond_to do |format|
      if @bedroom_types
        format.html
        format.js
        format.json { render json: @bedroom_types }
      end
    end
  end

  def new
    @bedroom_type = BedroomType.new
  end

  def create
    @bedroom_type = BedroomType.create(params.require(:bedroom_type))

    respond_to do |format|
      if @bedroom_type.save
        format.html { redirect_to admin_bedroom_types_path, notice: 'Bedroom type created successfully' }
        format.js { render js: "window.location='#{admin_bedroom_types_path}'", status: :created }
        format.json { render json: @bedroom_type, status: :created, location: [:admin, @bedroom_type] }
      else
        format.html { render action: 'new', alert: @bedroom_type.errors.full_messages.join('. ') }
        format.js { render text: @bedroom_type.errors.full_messages.join('. '), status: :unprocessable_entity }
        format.json { render json: @bedroom_type.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @bedroom_type = BedroomType.find_by_id(params[:id])
  end

  def update
    @bedroom_type = BedroomType.find_by_id(params[:id])

    respond_to do |format|
      if @bedroom_type
        if @bedroom_type.update_attributes(params.require(:bedroom_type))
          format.html { redirect_to edit_admin_bedroom_type_path(@bedroom_type), notice: "Bedroom type #{@bedroom_type.name} updated successfully" }
          format.js { render nothing: true, status: :ok }
          format.json { render json: @bedroom_type, status: :ok, location: [:admin, @bedroom_type] }
        else
          format.html { render :edit, alert: @bedroom_type.errors.full_messages.join('. ') }
          format.js { render text: @bedroom_type.errors.full_messages.join('. '), status: :unprocessable_entity }
          format.json { render json: @bedroom_type.errors.full_messages, status: :unprocessable_entity }
        end
      else
        format.html { redirect_back fallback_location: admin_bedroom_types_path, alert: "Cannot find bedroom type to update with id #{params[:id]}" }
        format.js { render text: 'bedroom type not found', status: :not_found }
        format.json { render json: '{"error": "bedroom type not found"}', status: :not_found }
      end
    end
  end

  def destroy
    @bedroom_type = BedroomType.find_by_id(params[:id])

    respond_to do |format|
      if @bedroom_type
        if @bedroom_type.destroy
          format.html { redirect_to admin_bedroom_types_url, notice: 'Bedroom type deleted successfully' }
          format.js { render nothing: true, status: :ok }
          format.json { render json: @bedroom_type, status: :ok }
        else
          format.html { redirect_to :back, alert: @bedroom_type.errors.full_messages.join('. ') }
          format.js { render text: @bedroom_type.errors.full_messages.join('. '), status: :unprocessable_entity }
          format.json { render json: @bedroom_type.errors.full_messages, status: :unprocessable_entity }
        end
      else
        format.html { redirect_back fallback_location: admin_bedroom_types_url, alert: "Cannot find bedroom type to delete with id #{params[:id]}" }
        format.js { render text: 'bedroom type to delete not found', status: :not_found }
        format.json { render json: '{"error": "bedroom type to delete not found"}', status: :not_found }
      end
    end
  end
end

app/views/admin/bedroom_types/_form.html.haml
.container-fluid.h-100.bg-light.text-dark
  .row.justify-content-center.align-items-center
    %h1
      = @action.capitalize
      bedroom type
  %hr/
  .row.justify-content-center.align-items-center.h-100
    .col.col-sm-6.col-md-6.col-lg-4.col-xl-3
      = form_for [:admin, @bedroom_type], html: {id: "bedroom-type-form"}, remote: true do |f|
        .input-group.mb-3
          %span.input-group-text= BedroomType.human_attribute_name(:name)
          = f.text_field :name, class: "form-control"
        = f.submit submit_text(@action), class: "btn btn-primary"
        = link_to "Back", :back, class: "btn btn-danger"

app/views/admin/bedroom_types/_table.html.haml
.table-responsive
  %table.table.caption-top
    %caption
      Bedroom Types
      .float-end
        = render "layouts/pagination_limit"
    %thead.table-dark
      %tr
        %th{scope: "col"} #
        %th{scope: "col"}= BedroomType.human_attribute_name(:name)
        %th{colspan: "3"}
    %tbody
      - @bedroom_types.each do |bedroom_type|
        %tr
          %th{scope: "row"}= bedroom_type.id
          %td= bedroom_type.name
          %td
            .btn-group.btn-group-sm{"aria-label" => "Action buttons", role: "group"}
              = link_to 'Edit', edit_admin_bedroom_type_path(bedroom_type), remote: true, class: 'btn btn-warning'
              = link_to 'Delete', admin_bedroom_type_path(bedroom_type), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this bedroom type ?' }
  .d-flex.justify-content-between
    %div
      = link_to "Create new bedroom type", new_admin_bedroom_type_path, remote: true, class: "btn btn-primary"
    = render "layouts/pagination_navigation"

app/views/admin/bedroom_types/edit.html.haml
= render 'form'

app/views/admin/bedroom_types/edit.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'form') %>');
$('form#bedroom-type-form[data-remote="true"]').on('ajax:success', function(e, data, status, xhr) {
    // if ajax is success set the default value to the current value so it doesnt reset on the old value when an error occured.
    Array.from(e.currentTarget.elements).map((el) => el.defaultValue = el.value);
    alert('Bedroom type <%= @bedroom_type.name %> updated successfully', 'success');
}).on('ajax:error', function(e, xhr, status, error) {
    e.target.reset();
    alert(xhr.responseText, 'danger', 0);
});

app/views/admin/bedroom_types/index.html.haml
= render "table"

app/views/admin/bedroom_types/index.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'table') %>');

app/views/admin/bedroom_types/new.html.haml
= render 'form'

app/views/admin/bedroom_types/new.js.erb
$('#page-content').empty();
$('#page-content').append('<%= escape_javascript(render partial: 'form') %>');
$('form#bedroom-type-form[data-remote="true"]').on('ajax:error', function(e, xhr, status, error) {
    alert(xhr.responseText, 'danger', 0);
});